spring:
    application:
        name: Rest Api Demo
    datasource:
        driver-class-name: org.h2.Driver
        username: admin
        password: 123
        url: "jdbc:h2:mem:todoapp;DB_CLOSE_ON_EXIT=FALSE"
    h2:
        console:
            enable: true
            path: /h2-console
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: create-drop




